---
- name: Set the system's hostname to the inventory_hostname
  hostname:
    name: "{{ inventory_hostname }}"
  become: true

- name: "Update serverName in {{ splunk_home }}/etc/system/local/server.conf"
  lineinfile:
    dest: "{{ splunk_home }}/etc/system/local/server.conf"
    state: present
    regexp: "^serverName = .*"
    line: "serverName = {{ ansible_hostname }}"
  become: true
  become_user: "{{ splunk_nix_user }}"
  notify: restart splunk

- name: "Update host in {{ splunk_home }}/etc/system/local/inputs.conf"
  lineinfile:
    dest: "{{ splunk_home }}/etc/system/local/inputs.conf"
    state: present
    regexp: "^host = .*"
    line: "host = {{ ansible_hostname }}"
  become: true
  become_user: "{{ splunk_nix_user }}"
  notify: restart splunk
