---
- name: Stop Splunk
  include_tasks: splunk_stop.yml

- name: Clean dispatch directory of all files
  shell: "rm -rf {{ splunk_home }}/var/run/splunk/dispatch/*"
  become: yes

- name: Start Splunk
  include_tasks: splunk_start.yml
