- name: Run splunk version command to check currently installed version
  command: "{{ splunk_home }}/bin/splunk version --answer-yes --auto-ports --no-prompt --accept-license"
  register: current_version
  become: true
  become_user: "{{ splunk_nix_user }}"
  changed_when: false

- name: Get Splunk version number only
  set_fact:
    splunk_v_num_only: "{{ current_version.stdout | regex_search ('\\d+\\.\\d+') }}"
