- name: Install splunk.secret
  copy:
    src: "{{ splunk_secret_file }}"
    dest: "{{ splunk_home }}/etc/auth/splunk.secret"
    owner: "{{ splunk_nix_user }}"
    group: "{{ splunk_nix_group }}"
  become: yes
  notify: restart splunk
  when: splunk_configure_secret
