---
- name: Configure DS URI in deploymentclient.conf
  ini_file:
    path: "{{ splunk_home }}/etc/system/local/deploymentclient.conf"
    section: 'target-broker:deploymentServer'
    option: targetUri
    value: "{{ splunk_uri_ds }}"
    owner: "{{ splunk_nix_user }}"
    group: "{{ splunk_nix_group }}"
    mode: 0644
  become: true
  notify: restart splunk
  when: splunk_uri_ds != 'undefined'

- name: Configure client name in deploymentclient.conf
  ini_file:
    path: "{{ splunk_home }}/etc/system/local/deploymentclient.conf"
    section: 'deployment-client'
    option: clientName
    value: "{{ clientName }}"
    owner: "{{ splunk_nix_user }}"
    group: "{{ splunk_nix_group }}"
    mode: 0644
  become: true
  notify: restart splunk
  when: clientName != 'undefined'
