---
- name: Configure idxc member
  command: "{{ splunk_home }}/bin/splunk edit cluster-config -mode peer -auth {{ splunk_auth }} -master_uri {{ splunk_uri_cm }} -replication_port {{ splunk_idxc_rep_port }} -secret {{ splunk_idxc_key }}"
  become: true
  become_user: "{{ splunk_nix_user }}"
  register: shc_init_result
  changed_when: shc_init_result.rc == 0
  failed_when: shc_init_result.rc != 0
  notify: restart splunk
  no_log: true
