---
- name: Run splunk version command to check currently installed version
  command: "{{ splunk_home }}/bin/splunk version --answer-yes --auto-ports --no-prompt --accept-license"
  register: current_version
  become: true
  become_user: "{{ splunk_nix_user }}"
  changed_when: false

- name: Set splunk version number
  set_fact:
    splunk_v_num_only: "{{ current_version.stdout | regex_search ('\\d+\\.\\d+\\.\\d+') }}"

# Splunk version < 8.1.X supports mode=master
# https://docs.splunk.com/Documentation/Splunk/8.0.9/Indexer/Configuremasterwithserverconf
- name: Configure clustering stanza for cluster manager node on Splunk version < 8.1.X
  ini_file:
    path: "{{ splunk_home }}/etc/system/local/server.conf"
    section: clustering
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    mode: 0644
    owner: "{{ splunk_nix_user }}"
    group: "{{ splunk_nix_group }}"
  become: true
  notify: restart splunk
  loop:
    - { option: "mode", value: "master" }
    - { option: "replication_factor", value: "{{ splunk_idxc_rf }}" }
    - { option: "search_factor", value: "{{ splunk_idxc_sf }}" }
    - { option: "pass4SymmKey", value: "{{ splunk_idxc_key }}" }
    - { option: "cluster_label", value: "{{ splunk_idxc_label }}" }
  when: splunk_v_num_only_url is version('8.1.0','<') or splunk_v_num_only is version('8.1.0','<')

# Splunk version >= 8.1.X supports mode=manager
# https://docs.splunk.com/Documentation/Splunk/latest/Indexer/Configuremanagerwithserverconf
- name: Configure clustering stanza for cluster manager node on Splunk version >= 8.1.X
  ini_file:
    path: "{{ splunk_home }}/etc/system/local/server.conf"
    section: clustering
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    mode: 0644
    owner: "{{ splunk_nix_user }}"
    group: "{{ splunk_nix_group }}"
  become: true
  notify: restart splunk
  loop:
    - { option: "mode", value: "manager" }
    - { option: "replication_factor", value: "{{ splunk_idxc_rf }}" }
    - { option: "search_factor", value: "{{ splunk_idxc_sf }}" }
    - { option: "pass4SymmKey", value: "{{ splunk_idxc_key }}" }
    - { option: "cluster_label", value: "{{ splunk_idxc_label }}" }
  when: splunk_v_num_only_url is version('8.1.0','>=') or splunk_v_num_only is version('8.1.0','>=')
