---
# This task MUST be called by configure_apps.yml to work correctly. Do NOT call this task directly via the deployment_task var!
- name: Set correct handler for master-apps
  set_fact:
    handler: "apply indexer cluster bundle"
  when: app_dest == 'etc/master-apps'

- name: Set correct handler for deployment-apps
  set_fact:
    handler: "reload deployment server"
  when: app_dest == 'etc/deployment-apps'

- name: Set correct handler for shcluster/apps
  set_fact:
    handler: "apply shcluster-bundle"
  when: app_dest == 'etc/shcluster/apps'

- name: "Set default restart splunk handler for all other paths (e.g. etc/auth)"
  set_fact:
    handler: "restart splunk"
  when:
    - app_dest != 'etc/shcluster/apps'
    - app_dest != 'etc/deployment-apps'
    - app_dest != 'etc/master-apps'

# Note: By using the synchronize module, if the repo already exists on the target host, we are able to only update the diff while preserving the local/ folder
- name: "Synchronize {{ item.name }} repo from local Ansible host to {{ splunk_home }}/{{ app_dest }}/{{ item.name }} on remote host"
  synchronize:
    src: "{{ app_src }}"
    dest: "{{ splunk_home }}/{{ app_dest }}/"
    recursive: yes
    delete: yes
    checksum: yes
    rsync_opts:
      - "--prune-empty-dirs"
      - "--itemize-changes"
      - "--no-owner"
      - "--no-group"
      - "--no-times"
  become: yes
  become_user: "{{ splunk_nix_user }}"
  notify: "{{ handler }}"

- name: Ensure correct permissions are set
  file:
    path: "{{ splunk_home }}/{{ app_dest }}/{{ item.name }}"
    owner: "{{ splunk_nix_user }}"
    group: "{{ splunk_nix_group }}"
    recurse: yes
  become: yes
