---
# Molecule converge playbook
# This playbook applies the Splunk role to create a complete cluster

- name: Deploy Cluster Manager first
  hosts: clustermanager
  become: true
  roles:
    - role: splunk
  vars:
    # Override installation path for testing
    splunk_home: /opt/splunk
    splunk_install_path: /opt

- name: Deploy License Master and DMC
  hosts: licensemaster
  become: true
  roles:
    - role: splunk
  vars:
    splunk_home: /opt/splunk
    splunk_install_path: /opt

- name: Deploy Deployment Server
  hosts: deploymentserver
  become: true
  roles:
    - role: splunk
  vars:
    splunk_home: /opt/splunk
    splunk_install_path: /opt

- name: Deploy Indexers (wait for Cluster Manager to be ready)
  hosts: indexer
  become: true
  serial: 1
  roles:
    - role: splunk
  vars:
    splunk_home: /opt/splunk
    splunk_install_path: /opt

- name: Deploy Search Head Deployer
  hosts: shdeployer
  become: true
  roles:
    - role: splunk
  vars:
    splunk_home: /opt/splunk
    splunk_install_path: /opt

- name: Deploy Search Head Cluster
  hosts: shcluster
  become: true
  serial: 1
  roles:
    - role: splunk
  vars:
    splunk_home: /opt/splunk
    splunk_install_path: /opt

- name: Deploy Universal Forwarders
  hosts: uf
  become: true
  roles:
    - role: splunk
  vars:
    splunk_home: /opt/splunkforwarder
    splunk_install_path: /opt