FROM lscr.io/linuxserver/webtop:ubuntu-xfce

# Minimal test - just set environment
ENV PUID=1000
ENV PGID=1000
ENV TZ=America/New_York
ENV TITLE="Test Webtop"

# Expose standard ports
EXPOSE 3000 3001