---
# Base inventory - used by both Molecule and Ansible
# Container names = hostnames within Docker network
all:
  vars:
    ansible_user: ansible
    ansible_ssh_private_key_file: /home/ansible/.ssh/id_rsa
    ansible_ssh_common_args: -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
  children:
    full:
      children:
        clustermanager:
          hosts:
            splunk-master:
              # Custom apps for cluster manager
              git_apps:
                - git_project: test/splunk_apps/
                  git_version: main
                  name: cluster_manager_app

        licensemaster:
          hosts:
            splunk-license:
              # License server specific config
              git_apps:
                - git_project: test/splunk_apps/
                  git_version: main
                  name: license_server_app

        dmc:
          hosts:
            splunk-license:  # DMC on license server for testing

        deploymentserver:
          hosts:
            splunk-fwdmanager:
              # Deployment server apps
              git_apps:
                - git_project: test/splunk_apps/
                  git_version: main
                  name: deployment_server_app

        indexer:
          hosts:
            splunkapp-prod01:
              splunk_idxc_site: site1
            splunkapp-prod02:
              splunk_idxc_site: site2

        indexer_site1:
          hosts:
            splunkapp-prod01:

        indexer_site2:
          hosts:
            splunkapp-prod02:

        shcluster:
          hosts:
            splunkshc-prod01:
            splunkshc-prod02:

        shdeployer:
          hosts:
            splunk-deploy:
              # Search head deployer apps - comprehensive test list
              git_apps:
                - git_project: test/splunk_apps/
                  git_version: main
                  name: test_search_app
                - git_project: test/splunk_apps/
                  git_version: main
                  name: test_dashboard_app
                - git_project: test/splunk_apps/
                  git_version: main
                  name: test_lookup_app
              target_shc_group_name: shcluster

        uf:
          hosts:
            splunk-uf01:
              # Universal forwarder specific config
              clientName: test-uf01
              splunk_uri_ds: "splunk-fwdmanager:8089"

    # Git server - separate from Splunk infrastructure (no SSH via ansible-role-for-splunk)
    git_server:
      hosts:
        git-server:
          ansible_user: root
          ansible_password: "Password1!"
