---
# Verify infrastructure is ready
- hosts: full:!git_server:!ansible_controller
  gather_facts: false
  vars:
    ansible_connection: docker  # Use Docker for verification (not SSH)
  tasks:
    - name: Test infrastructure setup
      command: echo "Infrastructure setup verified - containers created and SSH keys distributed to {{ inventory_hostname }}"
      register: infra_test

    - name: Display infrastructure test result
      debug:
        msg: "{{ infra_test.stdout }}"

    - name: Verify systemd is running
      command: systemctl is-active systemd
      register: systemd_check
      ignore_errors: true

    - name: Display systemd status
      debug:
        msg: "Systemd status: {{ systemd_check.stdout | default('not running') }}"