---
# handlers file for splunk role
# handlers are run in the order defined in this file
# thus "set ulimits in init.d" has been placed at the top to ensure it runs before splunk is started
- name: set ulimits in init.d
  lineinfile:
    path: /etc/init.d/splunk
    insertafter: ^\s+echo Starting Splunk\.\.\.$
    line: "{{ item }}"
    state: present
  loop:
    - ulimit -Hn 65536
    - ulimit -Sn 32768
  become: yes
  ignore_errors: true
  when: splunk_use_initd and ansible_os_family == "RedHat" and ansible_distribution_major_version|int > 6

- name: update init.d to accept license
  replace:
    path: /etc/init.d/splunk
    regexp: '(start --no-prompt --answer-yes)$'
    replace: '\1 --accept-license'
  become: yes
  when: splunk_use_initd

- name: update systemd
  lineinfile:
    path: "/etc/systemd/system/{{ splunk_server }}.service"
    section: Service
    options: "{{ item.option }}"
    value: "{{ item.value }}"
  loop:
    - { option: "ExecStart", value: "{{ splunk_home }}/bin/splunk start --accept-license --answer-yes --no-prompt" }
    - { option: "ExecStop", value: "{{ splunk_home }}/bin/splunk start stop" }
    - { option: "ExecReload", value: "{{ splunk_home }}/bin/splunk restart" }
    - { option: "Restart", value: "on-failure" }
    - { option: "RestartSec", value: "30s" }
    - { option: "TimeoutStopSec", value: "10min" }

- name: reload systemctl daemon
  systemd:
    daemon_reload: yes
  become: yes

- name: stop splunk
  service:
    name: "{{ splunk_service }}"
    state: stopped
  become: yes

- name: start splunk
  service:
    name: "{{ splunk_service }}"
    state: started
  become: yes

- name: apply indexer cluster bundle
  shell: "{{ splunk_home }}/bin/splunk apply cluster-bundle --answer-yes --skip-validation -auth {{ splunk_auth }}"
  become: yes
  become_user: "{{ splunk_nix_user }}"
  no_log: true
  when: "'clustermaster' in group_names"

- name: reload deployment server
  shell: "{{ splunk_home }}/bin/splunk reload deploy-server -auth {{ splunk_auth }}"
  become: yes
  become_user: "{{ splunk_nix_user }}"
  no_log: true
  when: "'deploymentserver' in group_names"

- name: apply shcluster-bundle
  shell: "{{ splunk_home }}/bin/splunk apply shcluster-bundle -preserve-lookups true --answer-yes -auth {{ splunk_auth }} -target {{ deploy_target }}"
  become: yes
  become_user: "{{ splunk_nix_user }}"
  no_log: true
  when: "'shdeployer' in group_names and deploy_target is defined"

- name: restart splunk
  service:
    name: "{{ splunk_service }}"
    state: restarted
  become: yes

- name: restart auditd service
  command: service auditd condrestart
  become: yes

