---
# Molecule converge playbook for day0
# Installs Splunk on target hosts using remote URLs

# Setup role variables for Splunk installation
- name: Setup Splunk installation variables
  hosts: all:!ansible_controller:!git_server:!jumpbox
  gather_facts: true
  # SSH vars now come from inventory group_vars/all.yml
  tasks:
    - name: Set Splunk installation variables
      set_fact:
        splunk_install_app: true
        splunk_build_remote_src: true
        splunk_install_method: "package"
        splunk_home: "/opt/splunk"
        splunk_nix_home: "/opt/splunk"
        splunk_install_path: "/opt"

# Import the main Splunk installation playbook (inherits SSH from inventory)
- name: Install Splunk on target hosts
  hosts: all:!ansible_controller:!git_server:!jumpbox
  roles:
    - ../../../roles/splunk
  serial: 50
  vars:
    deployment_task: check_splunk.yml
    splunk_install_app: true
    splunk_build_remote_src: true
    splunk_install_method: "package"
    splunk_home: "/opt/splunk"
    splunk_nix_home: "/opt/splunk"
    splunk_install_path: "/opt"