---
# Molecule converge playbook for day0
# Installs Splunk on target hosts

# Copy Splunk binaries to ansible-controller for distribution
- name: Copy Splunk binaries to ansible-controller
  hosts: ansible_controller
  gather_facts: false
  tasks:
    - name: Create software directory
      file:
        path: /home/ansible/software
        state: directory
        mode: '0755'

    - name: Copy Splunk Enterprise binary
      copy:
        src: /workspace/testing/software/splunk-9.0.4-de405f4a7979-Linux-x86_64.tgz
        dest: /home/ansible/software/
        mode: '0644'
      ignore_errors: true

    - name: Copy Splunk Universal Forwarder binary
      copy:
        src: /workspace/testing/software/splunkforwarder-9.0.4-de405f4a7979-Linux-x86_64.tgz
        dest: /home/ansible/software/
        mode: '0644'
      ignore_errors: true

# Setup role variables for Splunk installation
- name: Setup Splunk installation variables
  hosts: all:!ansible_controller:!git_server:!jumpbox
  gather_facts: true
  tasks:
    - name: Set Splunk installation variables
      set_fact:
        splunk_enterprise_package: "/home/ansible/software/splunk-9.0.4-de405f4a7979-Linux-x86_64.tgz"
        splunk_uf_package: "/home/ansible/software/splunkforwarder-9.0.4-de405f4a7979-Linux-x86_64.tgz"
        splunk_install_app: true
        splunk_build_remote_src: false
        splunk_install_method: "package"

# Import the main Splunk installation playbook
- import_playbook: ../../../playbooks/splunk_install_or_upgrade.yml