---
# Day 0 - Splunk Provisioning Scenario
# Initial deployment of Splunk via SSH connections (production-like)
# Uses native inventory approach with pre-release Molecule v25.9.0rc1

ansible:
  cfg:
    defaults:
      deprecation_warnings: false
  executor:
    backend: ansible-playbook
    args:
      ansible_playbook:
        - --inventory=${MOLECULE_SCENARIO_DIRECTORY}/../inventory/

dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml

driver:
  name: default

verifier:
  name: ansible

scenario:
  # Day 0 operations workflow - uses existing infrastructure
  destroy_sequence:
    - cleanup
  create_sequence:
    - dependency
  converge_sequence:
    - dependency
    - converge
  test_sequence:
    - dependency
    - converge
    - verify