---
# Bootstrap Lab Infrastructure Verification
# Ensures the lab infrastructure is properly set up for Splunk role testing

- name: Verify Lab Infrastructure is Ready
  hosts: all:!git_server:!jumpbox
  gather_facts: false
  tasks:
    - name: Verify containers are accessible
      raw: echo "Connectivity check successful"
      changed_when: false

    - name: Check SSH daemon is running on Splunk hosts
      raw: systemctl is-active sshd.service || systemctl is-active ssh.service
      register: ssh_status
      changed_when: false
      when: inventory_hostname != 'ansible-controller'

    - name: Verify SSH daemon status
      debug:
        msg: "SSH daemon is running on {{ inventory_hostname }}"
      when: inventory_hostname != 'ansible-controller' and ssh_status.stdout is search('active')

    - name: Verify ansible user exists
      raw: id ansible
      register: ansible_user_check
      changed_when: false
      when: inventory_hostname != 'ansible-controller'

    - name: Show ansible user status
      debug:
        msg: "Ansible user exists on {{ inventory_hostname }}"
      when: inventory_hostname != 'ansible-controller' and ansible_user_check.rc == 0

    - name: Verify SSH keys exist on controller
      raw: test -f {{ item }} && echo "exists" || echo "missing"
      loop:
        - /home/ansible/.ssh/id_rsa
        - /home/ansible/.ssh/id_rsa.pub
      register: ssh_key_check
      changed_when: false
      when: inventory_hostname == 'ansible-controller'

    - name: Show SSH key status
      debug:
        msg: "SSH key {{ item.item }} exists"
      loop: "{{ ssh_key_check.results }}"
      when: inventory_hostname == 'ansible-controller' and item.stdout is search('exists')

- name: Verify SSH Connectivity Matrix
  hosts: ansible_controller
  gather_facts: false
  vars:
    splunk_hosts:
      - splunk-master
      - splunk-license  
      - splunk-fwdmanager
      - splunkapp-prod01
      - splunkapp-prod02
      - splunkshc-prod01
      - splunkshc-prod02
      - splunk-deploy
      - splunk-uf01
  tasks:
    - name: Test SSH connectivity to all Splunk hosts
      command: >
        ssh -i /home/ansible/.ssh/id_rsa 
        -o StrictHostKeyChecking=no 
        -o ConnectTimeout=10 
        ansible@{{ item }} 
        "echo 'SSH connectivity verified'"
      loop: "{{ splunk_hosts }}"
      register: ssh_connectivity
      failed_when: ssh_connectivity.rc != 0

    - name: Verify ansible can run commands via SSH
      command: >
        ssh -i /home/ansible/.ssh/id_rsa 
        -o StrictHostKeyChecking=no 
        -o ConnectTimeout=10 
        ansible@{{ item }} 
        "sudo whoami"
      loop: "{{ splunk_hosts }}"
      register: sudo_test
      failed_when: sudo_test.rc != 0 or 'root' not in sudo_test.stdout

    - name: Create SSH connectivity report
      debug:
        msg:
          - "=== Lab Infrastructure Bootstrap Verification ==="
          - "✅ All {{ splunk_hosts | length }} Splunk hosts accessible via SSH"
          - "✅ Ansible user has sudo privileges on all hosts"  
          - "✅ SSH keys properly distributed"
          - "✅ Lab infrastructure ready for Splunk role testing"
          - ""
          - "Next steps:"
          - "  1. Run Splunk role testing: task test-splunk-role"
          - "  2. Access web lab: task open-lab (http://localhost:3000)"

- name: Verify Git Server
  hosts: git_server
  gather_facts: false
  tasks:
    - name: Check Gitea API accessibility
      raw: curl -s -o /dev/null -w "%{http_code}" http://localhost:8929/api/v1/version
      register: gitea_status
      changed_when: false

    - name: Show Gitea status info
      debug:
        msg: "✅ Gitea server ready - HTTP Status: {{ gitea_status.stdout }}"
      when: gitea_status.stdout == "200"