---
# Bootstrap Lab Infrastructure Verification
# Ensures the lab infrastructure is properly set up for Splunk role testing

- name: Verify Lab Infrastructure is Ready
  hosts: all:!git_server
  gather_facts: false
  tasks:
    - name: Verify containers are accessible
      ping:

    - name: Check SSH daemon is running on Splunk hosts
      service_facts:
      when: inventory_hostname != 'ansible-controller'

    - name: Verify SSH daemon status
      assert:
        that:
          - ansible_facts.services['sshd.service'].state == 'running' or ansible_facts.services['ssh.service'].state == 'running'
        fail_msg: "SSH daemon is not running on {{ inventory_hostname }}"
        success_msg: "SSH daemon is running on {{ inventory_hostname }}"
      when: inventory_hostname != 'ansible-controller'

    - name: Verify ansible user exists
      getent:
        database: passwd
        key: ansible
      when: inventory_hostname != 'ansible-controller'

    - name: Verify SSH keys exist
      stat:
        path: "{{ item }}"
      loop:
        - /shared/ssh_keys/id_rsa
        - /shared/ssh_keys/id_rsa.pub
      register: ssh_key_stats

    - name: Assert SSH keys exist
      assert:
        that:
          - item.stat.exists
        fail_msg: "SSH key {{ item.item }} not found"
        success_msg: "SSH key {{ item.item }} exists"
      loop: "{{ ssh_key_stats.results }}"

- name: Verify SSH Connectivity Matrix
  hosts: ansible_controller
  gather_facts: false
  vars:
    splunk_hosts:
      - splunk-master
      - splunk-license  
      - splunk-fwdmanager
      - splunkapp-prod01
      - splunkapp-prod02
      - splunkshc-prod01
      - splunkshc-prod02
      - splunk-deploy
      - splunk-uf01
  tasks:
    - name: Test SSH connectivity to all Splunk hosts
      command: >
        ssh -i /workspace/.ssh/id_rsa 
        -o StrictHostKeyChecking=no 
        -o ConnectTimeout=10 
        ansible@{{ item }} 
        "echo 'SSH connectivity verified'"
      loop: "{{ splunk_hosts }}"
      register: ssh_connectivity
      failed_when: ssh_connectivity.rc != 0

    - name: Verify ansible can run commands via SSH
      command: >
        ssh -i /workspace/.ssh/id_rsa 
        -o StrictHostKeyChecking=no 
        -o ConnectTimeout=10 
        ansible@{{ item }} 
        "sudo whoami"
      loop: "{{ splunk_hosts }}"
      register: sudo_test
      failed_when: sudo_test.rc != 0 or 'root' not in sudo_test.stdout

    - name: Create SSH connectivity report
      debug:
        msg:
          - "=== Lab Infrastructure Bootstrap Verification ==="
          - "✅ All {{ splunk_hosts | length }} Splunk hosts accessible via SSH"
          - "✅ Ansible user has sudo privileges on all hosts"  
          - "✅ SSH keys properly distributed"
          - "✅ Lab infrastructure ready for Splunk role testing"
          - ""
          - "Next steps:"
          - "  1. Run Splunk role testing: task test-splunk-role"
          - "  2. Access web lab: task open-lab (http://localhost:3000)"

- name: Verify Git Server
  hosts: git_server
  gather_facts: false
  tasks:
    - name: Check Gitea API accessibility
      uri:
        url: http://localhost:8929/api/v1/version
        method: GET
        return_content: true
      register: gitea_version

    - name: Show Gitea version info
      debug:
        msg: "✅ Gitea server ready - Version: {{ (gitea_version.content | from_json).version }}"