---
# Day 1 Operations - Converge
# Performs operational tasks on running Splunk cluster using upstream playbooks

- name: Day 1 Splunk Operations - Service Restart
  hosts: all:!ansible_controller:!git_server:!jumpbox
  gather_facts: true
  tasks:
    - name: Include Splunk restart task from upstream role
      include_role:
        name: splunk
        tasks_from: splunk_restart.yml

- name: Day 1 Splunk Operations - Health Checks
  hosts: all:!ansible_controller:!git_server:!jumpbox
  gather_facts: true
  tasks:
    - name: Include Splunk status check from upstream role
      include_role:
        name: splunk
        tasks_from: check_splunk_status.yml

- name: Day 1 Splunk Operations - License Acceptance
  hosts: all:!ansible_controller:!git_server:!jumpbox
  gather_facts: true
  tasks:
    - name: Include Splunk license acceptance from upstream role
      include_role:
        name: splunk
        tasks_from: splunk_license_accept.yml