---
# Day 1 - Splunk Operations Scenario
# Operational tasks on running Splunk cluster (restart, backup, maintenance)
# Assumes day0 provisioning already completed and Splunk is running

driver:
  name: docker

platforms:
  - name: splunk-master
    groups:
      - clustermanager
  - name: splunk-license
    groups:
      - licensemaster
  - name: splunk-deploy
    groups:
      - deploymentserver
  - name: splunk-fwdmanager
    groups:
      - forwardermanager
  - name: splunkshc-prod01
    groups:
      - shcluster
      - shdeployer
  - name: splunkshc-prod02
    groups:
      - shcluster
  - name: splunkapp-prod01
    groups:
      - searchheads
  - name: splunkapp-prod02
    groups:
      - searchheads
  - name: splunk-uf01
    groups:
      - uf
  - name: ansible-controller
    groups:
      - controller

dependency:
  name: shell
  command: echo "Day 1 operations assume existing lab infrastructure and day0 deployment"

provisioner:
  name: ansible
  inventory:
    host_list:
      - ../inventory/
  config_options:
    defaults:
      host_key_checking: False
      remote_user: ansible

verifier:
  name: ansible

scenario:
  # Day 1 operations workflow
  destroy_sequence:
    - cleanup
  create_sequence:
    - dependency
  converge_sequence:
    - dependency
    - converge
  test_sequence:
    - dependency
    - converge
    - verify