---
# Day 1 Operations - Verification
# Verifies operational tasks completed successfully

- name: Verify Day 1 Operations
  hosts: all:!ansible_controller:!git_server:!jumpbox
  gather_facts: true
  tasks:
    - name: Check if Splunk binary exists
      stat:
        path: "{{ item }}"
      register: splunk_binary
      loop:
        - /opt/splunk/bin/splunk
        - /opt/splunkforwarder/bin/splunk
      ignore_errors: true

    - name: Set Splunk binary path
      set_fact:
        splunk_bin: "{{ '/opt/splunk/bin/splunk' if splunk_binary.results[0].stat.exists | default(false) else '/opt/splunkforwarder/bin/splunk' }}"
        splunk_home: "{{ '/opt/splunk' if splunk_binary.results[0].stat.exists | default(false) else '/opt/splunkforwarder' }}"
      when: splunk_binary.results[0].stat.exists | default(false) or splunk_binary.results[1].stat.exists | default(false)

    - name: Debug Splunk binary path
      debug:
        msg: "Splunk binary path: {{ splunk_bin | default('Not found') }}"

    - name: Verify Splunk services are still running after operations (process check)
      shell: |
        if [ -d "/opt/splunk" ]; then
          ps aux | grep -v grep | grep -q "/opt/splunk/bin/splunkd.*start" && echo "running" || echo "not running"
        elif [ -d "/opt/splunkforwarder" ]; then
          ps aux | grep -v grep | grep -q "/opt/splunkforwarder/bin/splunkd.*start" && echo "running" || echo "not running"
        else
          echo "not installed"
        fi
      register: splunk_final_status
      changed_when: false

    - name: Get detailed Splunk process information
      shell: ps aux | grep -v grep | grep -E 'splunkd|splunk'
      register: detailed_splunk_processes
      changed_when: false
      ignore_errors: true

    - name: Display detailed Splunk process information
      debug:
        msg: "{{ detailed_splunk_processes.stdout_lines | default(['No Splunk processes found']) }}"

    - name: Check Splunk log for startup issues
      shell: "grep -i 'error\|warn\|fail' {{ splunk_home }}/var/log/splunk/splunkd.log | tail -20 || echo 'No log file found'"
      register: splunk_logs
      changed_when: false
      ignore_errors: true
      when: splunk_home is defined

    - name: Display Splunk log issues
      debug:
        msg: "{{ splunk_logs.stdout_lines | default(['No log data available']) }}"
      when: splunk_home is defined
      
    - name: Confirm operational status
      assert:
        that:
          - splunk_final_status.stdout == "running"
        success_msg: "Day 1 operations completed successfully on {{ inventory_hostname }}"
        fail_msg: "Day 1 operations failed - Splunk not running on {{ inventory_hostname }}"

    - name: Summarize verification results
      debug:
        msg: |
          Splunk verification results for {{ inventory_hostname }}:
          - Binary exists: {{ splunk_bin is defined }}
          - Process status: {{ splunk_final_status.stdout }}
          - Process details: {{ 'Found' if detailed_splunk_processes.stdout_lines | default([]) | length > 0 else 'None detected' }}