---
# SSH connection overrides for Ansible deployment
# These override Molecule's default Docker connection settings

# Connection method override - SSH for realistic testing
ansible_user: ansible
ansible_connection: ssh
ansible_host: "{{ inventory_hostname }}"  # Container name = hostname in Docker network
ansible_ssh_private_key_file: /shared/ssh_keys/id_rsa
ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
ansible_python_interpreter: /usr/bin/python3

# Essential configuration from production inventory
splunk_backup: true
splunk_backup_path: "{{ splunk_home }}/.."
splunk_backup_tar: "splunk-test-backup.tar"

# Git configuration for app deployment testing
git_server: "git@git-server"  # Using lightweight git server container
git_key: "/tmp/test_git_key"  # Test key for git access
git_local_clone_path: ~/git_apps

# Splunk configuration - adapted for testing
splunk_home: /opt/splunk
splunk_install_path: /opt
splunk_nix_user: splunk
splunk_nix_group: splunk
splunk_admin_username: admin
splunk_admin_password: "Password123!"  # Test password
splunk_auth: "{{ splunk_admin_username }}:{{ splunk_admin_password }}"

# Cluster configuration for testing
splunk_idxc_key: test-indexer-key
splunk_idxc_rf: 1  # Reduced for testing
splunk_idxc_sf: 1  # Reduced for testing
splunk_idxc_rep_port: 9887
splunk_idxc_label: test-idxc

splunk_shc_key: test-searchhead-key
splunk_shc_label: test-shc
splunk_shc_rf: 2  # Reduced for testing
splunk_shc_rep_port: 8100
splunk_shc_target_group: shcluster

# Test versions - using stable versions for testing
splunk_version: 9.1.2
splunk_package_url_full: "https://download.splunk.com/products/splunk/releases/9.1.2/linux/splunk-9.1.2-b6b9c8185839-Linux-x86_64.tgz"
splunk_package_url_uf: "https://download.splunk.com/products/universalforwarder/releases/9.1.2/linux/splunkforwarder-9.1.2-b6b9c8185839-Linux-x86_64.tgz"